import { useEffect, useState } from 'react';
import { api } from '../services/api.js';
export default function AdminPage() {
  const [data, setData] = useState(null); const [listings, setListings] = useState([]); const [disputes, setDisputes] = useState([]); const [error, setError] = useState('');
  const load = () => Promise.all([api('/admin/analytics'), api('/admin/listings'), api('/admin/disputes')]).then(([metrics, listed, flagged]) => { setData(metrics); setListings(listed); setDisputes(flagged); }).catch((err) => setError(err.message)); useEffect(() => { load(); }, []);
  async function remove(id) { try { await api(`/admin/listings/${id}/remove`, { method: 'PATCH' }); load(); } catch (err) { setError(err.message); } }
  async function review(id, status) { try { await api(`/admin/disputes/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); load(); } catch (err) { setError(err.message); } }
  if (error && !data) return <p className="error page-message">{error}</p>;
  return <section className="admin"><p className="eyebrow">Administrator</p><h1>Platform overview</h1>{data && <div className="metrics">{Object.entries(data).map(([key, value]) => <article key={key}><strong>{value}{key === 'requestConversionRate' ? '%' : ''}</strong><span>{key.replace(/([A-Z])/g, ' $1')}</span></article>)}</div>}<h2>Listing moderation</h2><div className="admin-table">{listings.map((listing) => <article key={listing._id}><span><b>{listing.title}</b><small>{listing.owner?.name} · {listing.status}</small></span>{listing.status !== 'removed' && <button className="secondary" onClick={() => remove(listing._id)}>Remove</button>}</article>)}</div><h2>Disputes</h2>{disputes.length === 0 ? <p>No disputes have been raised.</p> : <div className="admin-table">{disputes.map((dispute) => <article key={dispute._id}><span><b>{dispute.status}: {dispute.reason}</b><small>Opened by {dispute.openedBy?.name}</small></span><button className="secondary" onClick={() => review(dispute._id, dispute.status === 'open' ? 'reviewing' : 'resolved')}>{dispute.status === 'open' ? 'Review' : 'Resolve'}</button></article>)}</div>}{error && <p className="error">{error}</p>}</section>;
}
