import { useEffect, useState } from 'react';
import { api } from '../services/api.js';
export default function AdminPage() {
  const [data, setData] = useState(null); const [listings, setListings] = useState([]); const [disputes, setDisputes] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState('');
  const load = () => { setLoading(true); return Promise.all([api('/admin/analytics'), api('/admin/listings'), api('/admin/disputes')]).then(([metrics, listed, flagged]) => { setData(metrics); setListings(listed); setDisputes(flagged); }).catch((err) => setError(err.message)).finally(() => setLoading(false)); }; useEffect(() => { load(); }, []);
  async function remove(id) { setBusy(id); try { await api(`/admin/listings/${id}/remove`, { method: 'PATCH' }); await load(); } catch (err) { setError(err.message); } finally { setBusy(''); } }
  async function review(id, status) { setBusy(id); try { await api(`/admin/disputes/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); await load(); } catch (err) { setError(err.message); } finally { setBusy(''); } }
  return <section className="admin"><p className="eyebrow">Administrator</p><h1>Platform overview</h1><p>Moderation and activity are drawn from the current marketplace records.</p>{loading && <p className="loading" role="status">Loading platform data…</p>}{error && <p className="error" role="alert">{error}</p>}{data && <div className="metrics">{Object.entries(data).map(([key, value]) => <article key={key}><strong>{value}{key === 'requestConversionRate' ? '%' : ''}</strong><span>{key.replace(/([A-Z])/g, ' $1')}</span></article>)}</div>}<h2>Listing moderation</h2>{!loading && listings.length === 0 ? <div className="empty">No listings require review.</div> : <div className="admin-table">{listings.map((listing) => <article key={listing._id}><span><b>{listing.title}</b><small>{listing.owner?.name} · {listing.status}</small></span>{listing.status !== 'removed' && <button disabled={busy === listing._id} className="secondary" onClick={() => remove(listing._id)}>{busy === listing._id ? 'Removing…' : 'Remove'}</button>}</article>)}</div>}<h2>Disputes</h2>{!loading && disputes.length === 0 ? <div className="empty">No disputes have been raised.</div> : <div className="admin-table">{disputes.map((dispute) => <article key={dispute._id}><span><b><span className={`status ${dispute.status}`}>{dispute.status}</span> {dispute.reason}</b><small>Opened by {dispute.openedBy?.name}</small></span><button disabled={busy === dispute._id} className="secondary" onClick={() => review(dispute._id, dispute.status === 'open' ? 'reviewing' : 'resolved')}>{busy === dispute._id ? 'Saving…' : dispute.status === 'open' ? 'Review' : 'Resolve'}</button></article>)}</div>}</section>;
}
