import { useEffect, useState } from 'react';
import { api } from '../services/api.js';
import { useAuth } from '../context/AuthContext.jsx';
const stamp = (date) => new Date(date).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' });
export default function ChatPage() {
  const { user } = useAuth(); const [conversations, setConversations] = useState([]); const [selected, setSelected] = useState(''); const [messages, setMessages] = useState([]); const [text, setText] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false);
  useEffect(() => { api('/messages/conversations').then((data) => { setConversations(data); if (data[0]) setSelected(data[0]._id); }).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, []);
  const loadMessages = () => selected && api(`/messages/${selected}`).then(setMessages).catch((err) => setError(err.message));
  useEffect(() => { loadMessages(); const timer = setInterval(loadMessages, 12000); return () => clearInterval(timer); }, [selected]);
  async function send(event) { event.preventDefault(); if (!text.trim()) return; setSending(true); setError(''); try { const message = await api(`/messages/${selected}`, { method: 'POST', body: JSON.stringify({ text: text.trim() }) }); setMessages((items) => [...items, message]); setText(''); } catch (err) { setError(err.message); } finally { setSending(false); } }
  const active = conversations.find((swap) => swap._id === selected);
  return <section className="chat" aria-label="Swap conversations"><div className="chat-list"><p className="eyebrow">Negotiations</p><h2>Conversations</h2>{loading && <p className="loading">Loading conversations…</p>}{!loading && conversations.length === 0 && <p className="empty">No conversations yet. A chat opens once a swap request is sent.</p>}{conversations.map((swap) => <button type="button" aria-pressed={selected === swap._id} className={`conversation ${selected === swap._id ? 'selected' : ''}`} onClick={() => setSelected(swap._id)} key={swap._id}>{swap.offeredItem.title} ↔ {swap.requestedItem.title}<small>{swap.status.replace('_', ' ')}</small></button>)}</div><div className="chat-window">{active ? <><div className="chat-context"><h2>{active.offeredItem.title} ↔ {active.requestedItem.title}</h2><p>{active.status.replace('_', ' ')} · Messages refresh automatically</p></div><div className="messages" aria-live="polite">{messages.length === 0 && <p className="empty">Start the negotiation with a message.</p>}{messages.map((message) => <div className={`message ${message.sender._id === user.id ? 'mine' : ''}`} key={message._id}><b>{message.sender.name}</b><span>{message.text}</span><time dateTime={message.createdAt}>{stamp(message.createdAt)}</time></div>)}</div><form className="message-form" onSubmit={send}><input aria-label="Message" required value={text} maxLength="1000" onChange={(event) => setText(event.target.value)} placeholder="Write a message" /><button disabled={sending}>{sending ? 'Sending…' : 'Send'}</button></form></> : <p className="page-message">{loading ? 'Loading chat…' : 'Select a swap conversation.'}</p>}{error && <p className="error" role="alert">{error}</p>}</div></section>;
}
