import { useEffect, useMemo, useState } from 'react';
import { api } from '../services/api.js';
import { useAuth } from '../context/AuthContext.jsx';

export default function CommercePage() {
  const { user } = useAuth(); const [products, setProducts] = useState([]); const [services, setServices] = useState([]); const [orders, setOrders] = useState([]); const [requests, setRequests] = useState([]); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = () => Promise.all([api('/products'), api('/services'), api('/orders'), api('/service-requests')]).then(([p, s, o, r]) => { setProducts(p); setServices(s); setOrders(o); setRequests(r); }).catch((e) => setError(e.message));
  useEffect(() => { load(); }, []);
  const earnings = useMemo(() => orders.filter((order) => order.status === 'completed').reduce((sum, order) => sum + order.total, 0) + requests.filter((request) => request.status === 'completed').reduce((sum, request) => sum + (request.quotedPrice || 0), 0), [orders, requests]);
  async function change(path, action) { try { await api(path, { method: 'PATCH', body: JSON.stringify({ action }) }); setNotice('Status updated.'); load(); } catch (e) { setError(e.message); } }
  async function availability(event) { try { await api('/users/me/availability', { method: 'PATCH', body: JSON.stringify({ available: event.target.checked }) }); setNotice(event.target.checked ? 'You are available for requests.' : 'You are unavailable for new requests.'); } catch (e) { setError(e.message); } }
  const isEntrepreneur = user.role === 'entrepreneur';
  return <section className="dashboard"><div><p className="eyebrow">Transactions</p><h1>{isEntrepreneur ? 'Business management' : 'Your orders and requests'}</h1>{isEntrepreneur && <><label><input type="checkbox" defaultChecked={user.available} onChange={availability} /> Available for new service requests</label><div className="activity"><strong>₹{earnings.toLocaleString('en-IN')}</strong><span>completed-order earnings</span><strong>{orders.filter((o) => o.status === 'completed').length}</strong><span>completed orders</span><strong>{requests.filter((r) => r.status === 'completed').length}</strong><span>completed services</span></div></>}<h2>{isEntrepreneur ? 'Product orders' : 'Order history'}</h2>{orders.length ? <div className="admin-table">{orders.map((o) => <article key={o._id}><span><b>{o.product?.title}</b><small>₹{o.total} · {o.status} · {isEntrepreneur ? o.customer?.name : o.entrepreneur?.name}</small></span>{isEntrepreneur && o.status === 'pending' && <button onClick={() => change(`/orders/${o._id}`, 'confirm')}>Confirm</button>}{isEntrepreneur && o.status === 'confirmed' && <button onClick={() => change(`/orders/${o._id}`, 'complete')}>Complete</button>}{!isEntrepreneur && o.status === 'pending' && <button className="secondary" onClick={() => change(`/orders/${o._id}`, 'cancel')}>Cancel</button>}</article>)}</div> : <p>No orders yet.</p>}<h2>{isEntrepreneur ? 'Incoming service requests' : 'Service request history'}</h2>{requests.length ? <div className="admin-table">{requests.map((r) => <article key={r._id}><span><b>{r.service?.title}</b><small>{r.status} · {r.details} · {isEntrepreneur ? r.customer?.name : r.entrepreneur?.name}</small></span>{isEntrepreneur && r.status === 'pending' && <><button onClick={() => change(`/service-requests/${r._id}`, 'accept')}>Accept</button><button className="secondary" onClick={() => change(`/service-requests/${r._id}`, 'reject')}>Reject</button></>}{isEntrepreneur && r.status === 'accepted' && <button onClick={() => change(`/service-requests/${r._id}`, 'start')}>Start</button>}{isEntrepreneur && r.status === 'in_progress' && <button onClick={() => change(`/service-requests/${r._id}`, 'complete')}>Complete</button>}</article>)}</div> : <p>No service requests yet.</p>}{notice && <p className="success">{notice}</p>}{error && <p className="error">{error}</p>}</div><aside className="listing-form"><h2>Marketplace activity</h2><p>{products.length} available products</p><p>{services.length} available services</p><p>Orders and service requests are validated and recorded by the server.</p></aside></section>;
}
