import { useEffect, useState } from 'react';
import { api } from '../services/api.js';
import { useAuth } from '../context/AuthContext.jsx';
const initial = { title: '', type: '', brand: '', size: '', condition: 'good', estimatedSwapValue: '', location: '', imageUrls: '' };
const toForm = (item, location) => item ? { ...item, imageUrls: (item.images || []).join(', ') } : { ...initial, location };
export default function DashboardPage() {
  const { user } = useAuth(); const [form, setForm] = useState(toForm(null, user.location)); const [listings, setListings] = useState([]); const [swaps, setSwaps] = useState([]); const [editing, setEditing] = useState(null); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = () => { api('/clothing/mine').then(setListings).catch((err) => setError(err.message)); api('/swaps').then(setSwaps).catch(() => {}); };
  useEffect(() => { load(); }, []);
  function update(event) { setForm({ ...form, [event.target.name]: event.target.value }); }
  function edit(item) { setEditing(item._id); setForm(toForm(item, user.location)); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  function reset() { setEditing(null); setForm(toForm(null, user.location)); }
  async function submit(event) { event.preventDefault(); setError(''); setMessage(''); const data = { ...form, estimatedSwapValue: Number(form.estimatedSwapValue), images: form.imageUrls.split(',').map((url) => url.trim()).filter(Boolean) }; delete data.imageUrls; try { await api(editing ? `/clothing/${editing}` : '/clothing', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(data) }); setMessage(editing ? 'Listing updated.' : 'Your listing is live.'); reset(); load(); } catch (err) { setError(err.message); } }
  async function remove(id) { if (!window.confirm('Remove this listing? It will no longer appear in the marketplace.')) return; try { await api(`/clothing/${id}`, { method: 'DELETE' }); load(); } catch (err) { setError(err.message); } }
  const activeSwaps = swaps.filter((swap) => ['pending', 'accepted'].includes(swap.status)); const history = swaps.filter((swap) => ['rejected', 'cancelled', 'completed'].includes(swap.status));
  return <section className="dashboard"><div><p className="eyebrow">Your wardrobe</p><h1>Hello, {user.name}.</h1><p>{user.email} · {user.location}</p><div className="activity"><strong>{listings.filter((item) => item.status === 'available').length}</strong><span>available listings</span><strong>{activeSwaps.length}</strong><span>active swaps</span><strong>{history.length}</strong><span>past requests</span></div><h2>Your listings</h2>{listings.length === 0 ? <p>No listings yet.</p> : <div className="my-listings">{listings.map((item) => <article key={item._id}><b>{item.title}</b><small>{item.status} · ₹{item.estimatedSwapValue}</small><span><button className="text-action" onClick={() => edit(item)}>Edit</button><button className="text-action danger" onClick={() => remove(item._id)}>Remove</button></span></article>)}</div>}</div><form className="listing-form" onSubmit={submit}><h2>{editing ? 'Edit listing' : 'Add a clothing listing'}</h2><div className="two-col"><label>Title<input required name="title" value={form.title} onChange={update} placeholder="e.g. Indigo denim jacket" /></label><label>Type / category<input required name="type" value={form.type} onChange={update} placeholder="Jacket, dress, shoes…" /></label><label>Brand<input required name="brand" value={form.brand} onChange={update} /></label><label>Size<input required name="size" value={form.size} onChange={update} /></label><label>Condition<select name="condition" value={form.condition} onChange={update}><option>new with tags</option><option>like new</option><option>good</option><option>fair</option></select></label><label>Estimated swap value (₹)<input required min="1" type="number" name="estimatedSwapValue" value={form.estimatedSwapValue} onChange={update} /></label></div><label>Image URL(s), comma separated<input name="imageUrls" value={form.imageUrls} onChange={update} placeholder="https://…" /></label><label>City / location<input required name="location" value={form.location} onChange={update} /></label>{message && <p className="success">{message}</p>}{error && <p className="error">{error}</p>}<div className="form-actions"><button>{editing ? 'Save changes' : 'Publish listing'}</button>{editing && <button type="button" className="secondary" onClick={reset}>Cancel</button>}</div></form></section>;
}
