import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../services/api.js';
import { useAuth } from '../context/AuthContext.jsx';
export default function DetailPage() {
  const { id } = useParams(); const { user } = useAuth(); const [item, setItem] = useState(null); const [mine, setMine] = useState([]); const [suggestions, setSuggestions] = useState([]); const [offeredItem, setOfferedItem] = useState(''); const [initialMessage, setInitialMessage] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { api(`/clothing/${id}`).then(setItem).catch((err) => setError(err.message)); api(`/clothing/${id}/suggestions`).then(setSuggestions).catch(() => {}); }, [id]);
  useEffect(() => { if (user) api('/clothing/mine').then((items) => setMine(items.filter((entry) => entry.status === 'available'))).catch(() => {}); }, [user]);
  async function requestSwap(event) { event.preventDefault(); try { await api('/swaps', { method: 'POST', body: JSON.stringify({ offeredItem, requestedItem: id, initialMessage }) }); setMessage('Swap request sent.'); } catch (err) { setError(err.message); } }
  if (error && !item) return <p className="error page-message">{error}</p>; if (!item) return <p className="page-message">Loading listing…</p>;
  const own = user?.id === item.owner?._id;
  return <><section className="detail"><div className="detail-photo">{item.images?.[0] ? <img src={item.images[0]} alt={item.title} /> : item.type}</div><div><p className="eyebrow">{item.status}</p><h1>{item.title}</h1><p className="detail-brand">{item.brand} · Size {item.size}</p><p><b>Condition:</b> {item.condition}</p><p><b>Estimated swap value:</b> ₹{item.estimatedSwapValue.toLocaleString('en-IN')}</p><p><b>Location:</b> {item.location}</p><p>Listed by {item.owner?.name} in {item.owner?.location}. Contact details stay private until a swap is agreed.</p>{own ? <Link className="button inline" to="/dashboard">Manage this listing</Link> : !user ? <Link className="button inline" to="/login">Log in to request a swap</Link> : item.status !== 'available' ? <p>This item is not currently available for a new swap.</p> : <form className="swap-form" onSubmit={requestSwap}><h2>Propose a swap</h2>{mine.length ? <><label>Offer one of your available items<select required value={offeredItem} onChange={(event) => setOfferedItem(event.target.value)}><option value="">Choose your item</option>{mine.map((entry) => <option value={entry._id} key={entry._id}>{entry.title} — ₹{entry.estimatedSwapValue}</option>)}</select></label><label>Message (optional)<input maxLength="500" value={initialMessage} onChange={(event) => setInitialMessage(event.target.value)} placeholder="Why this would be a good swap…" /></label><button>Send swap request</button></> : <p>Add an available listing in your <Link to="/dashboard">dashboard</Link> before proposing a swap.</p>}{message && <p className="success">{message}</p>}{error && <p className="error">{error}</p>}</form>}</div></section>{suggestions.length > 0 && <section className="suggestions"><p className="eyebrow">Rule-based matches</p><h2>Similar value opportunities</h2>{suggestions.map(({ listing, sameLocation, comparison }) => <Link to={`/listings/${listing._id}`} key={listing._id}>{listing.title} · ₹{listing.estimatedSwapValue} · {sameLocation ? 'same city' : 'other city'} · {comparison.balance}</Link>)}</section>}</>;
}
