import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../services/api.js';

export default function ListingsPage() {
  const [listings, setListings] = useState([]); const [error, setError] = useState(''); const [filters, setFilters] = useState({ search: '', type: '', size: '', condition: '', brand: '', location: '' });
  useEffect(() => { const query = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); api(`/clothing?${query}`).then(setListings).catch((err) => setError(err.message)); }, [filters]);
  const update = (event) => setFilters({ ...filters, [event.target.name]: event.target.value });
  return <><section className="hero"><p className="eyebrow">A kinder wardrobe</p><h1>Give great clothes their next chapter.</h1><p>Discover thoughtfully listed pieces nearby and swap what you no longer wear.</p></section><section><div className="section-heading"><div><p className="eyebrow">Fresh listings</p><h2>Available to swap</h2></div></div><div className="filters"><input name="search" value={filters.search} onChange={update} placeholder="Search pieces or brands" /><input name="type" value={filters.type} onChange={update} placeholder="Category / type" /><input name="size" value={filters.size} onChange={update} placeholder="Size" /><select name="condition" value={filters.condition} onChange={update}><option value="">Any condition</option><option>new with tags</option><option>like new</option><option>good</option><option>fair</option></select><input name="brand" value={filters.brand} onChange={update} placeholder="Brand" /><input name="location" value={filters.location} onChange={update} placeholder="City" /></div>{error && <p className="error">{error}</p>}{!error && listings.length === 0 && <div className="empty">No listings match those filters yet.</div>}<div className="grid">{listings.map((item) => <Link className="listing" to={`/listings/${item._id}`} key={item._id}><div className="photo">{item.images?.[0] ? <img src={item.images[0]} alt={item.title} /> : <span>{item.type}</span>}</div><div className="listing-content"><div><h3>{item.title}</h3><p>{item.brand} · {item.size}</p></div><strong>₹{item.estimatedSwapValue.toLocaleString('en-IN')}</strong><footer>{item.condition} · {item.location} · {item.status}</footer></div></Link>)}</div></section></>;
}
