import { useEffect, useState } from 'react';
import { api } from '../services/api.js';
import { useAuth } from '../context/AuthContext.jsx';
export default function SwapsPage() {
  const { user } = useAuth(); const [swaps, setSwaps] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState('');
  const load = () => { setLoading(true); return api('/swaps').then(setSwaps).catch((err) => setError(err.message)).finally(() => setLoading(false)); }; useEffect(() => { load(); }, []);
  async function action(id, action) { setError(''); setBusy(`${id}:${action}`); try { await api(`/swaps/${id}`, { method: 'PATCH', body: JSON.stringify({ action }) }); await load(); } catch (err) { setError(err.message); } finally { setBusy(''); } }
  return <section className="requests"><p className="eyebrow">Exchange activity</p><h1>Swap requests</h1><p>Review incoming offers and keep track of your own requests in one place.</p>{loading && <p className="loading" role="status">Loading requests…</p>}{error && <p className="error" role="alert">{error}</p>}{!loading && !error && swaps.length === 0 && <div className="empty">No swap requests yet. Browse listings to propose your first exchange.</div>}{swaps.map((swap) => { const incoming = swap.recipient._id === user.id; const difference = swap.offeredItem.estimatedSwapValue - swap.requestedItem.estimatedSwapValue; const waiting = (actionName) => busy === `${swap._id}:${actionName}`; return <article className="request" key={swap._id}><div><p className="eyebrow">{incoming ? 'Incoming' : 'Outgoing'}</p><span className={`status ${swap.status}`}>{swap.status.replace('_', ' ')}</span><h2>{swap.offeredItem.title} <span>for</span> {swap.requestedItem.title}</h2><p>{incoming ? `${swap.requester.name} is offering` : 'You offered'} <b>{swap.offeredItem.title}</b> for <b>{swap.requestedItem.title}</b>.</p><p className="value-note">Offer ₹{swap.offeredItem.estimatedSwapValue} · Request ₹{swap.requestedItem.estimatedSwapValue} · Difference ₹{Math.abs(difference)} ({Math.abs(difference) <= Math.max(swap.offeredItem.estimatedSwapValue, swap.requestedItem.estimatedSwapValue) * .15 ? 'close match' : 'discuss the difference'})</p>{swap.initialMessage && <p className="request-message">“{swap.initialMessage}”</p>}</div><div className="actions">{swap.status === 'pending' && incoming && <><button disabled={Boolean(busy)} onClick={() => action(swap._id, 'accept')}>{waiting('accept') ? 'Accepting…' : 'Accept'}</button><button disabled={Boolean(busy)} className="secondary" onClick={() => action(swap._id, 'reject')}>Reject</button></>}{swap.status === 'pending' && !incoming && <button disabled={Boolean(busy)} className="secondary" onClick={() => action(swap._id, 'cancel')}>Cancel</button>}{swap.status === 'accepted' && <button disabled={Boolean(busy)} onClick={() => action(swap._id, 'agree')}>Confirm agreement</button>}{swap.status === 'agreed' && <button disabled={Boolean(busy)} onClick={() => action(swap._id, 'start')}>Start exchange</button>}{['accepted', 'agreed', 'in_progress'].includes(swap.status) && <button disabled={Boolean(busy)} className="secondary" onClick={() => action(swap._id, 'complete')}>Mark completed</button>}</div></article>; })}</section>;
}
