import { Router } from 'express';
import { calculateListingValue, createClothing, getClothing, listClothing, myClothing, removeClothing, suggestions, updateClothing } from '../controllers/clothingController.js';
import { requireAuth } from '../middleware/auth.js';
const router = Router();
router.get('/mine', requireAuth, myClothing);
router.post('/value', calculateListingValue);
router.get('/:id/suggestions', suggestions);
router.route('/').get(listClothing).post(requireAuth, createClothing);
router.route('/:id').get(getClothing).patch(requireAuth, updateClothing).delete(requireAuth, removeClothing);
export default router;
