import Clothing from '../models/Clothing.js';
import Dispute from '../models/Dispute.js';
import SwapRequest from '../models/SwapRequest.js';
import User from '../models/User.js';
import Order from '../models/Order.js';
import ServiceRequest from '../models/ServiceRequest.js';
import Category from '../models/Category.js';
import Complaint from '../models/Complaint.js';
import Review from '../models/Review.js';

export async function users(req, res, next) { try { res.json(await User.find().select('name email location role createdAt').sort({ createdAt: -1 })); } catch (error) { next(error); } }
export async function listings(req, res, next) { try { res.json(await Clothing.find().populate('owner', 'name email').sort({ createdAt: -1 })); } catch (error) { next(error); } }
export async function moderateListing(req, res, next) { try { const listing = await Clothing.findById(req.params.id); if (!listing) return res.status(404).json({ message: 'Listing not found.' }); listing.status = 'removed'; await listing.save(); res.json(listing); } catch (error) { next(error); } }
export async function swaps(req, res, next) { try { res.json(await SwapRequest.find().populate('requester recipient', 'name email').populate('offeredItem requestedItem', 'title').sort({ createdAt: -1 })); } catch (error) { next(error); } }
export async function analytics(req, res, next) { try { const [totalListings, activeUsers, requests, completed, activeListings] = await Promise.all([Clothing.countDocuments(), User.countDocuments(), SwapRequest.countDocuments(), SwapRequest.countDocuments({ status: 'completed' }), Clothing.countDocuments({ status: 'available' })]); res.json({ totalListings, activeUsers, swapRequests: requests, completedSwaps: completed, activeListings, requestConversionRate: requests ? Math.round((completed / requests) * 100) : 0 }); } catch (error) { next(error); } }
export async function disputes(req, res, next) { try { res.json(await Dispute.find().populate('openedBy participants', 'name email').populate('swap').sort({ createdAt: -1 })); } catch (error) { next(error); } }
export async function updateDispute(req, res, next) { try { const dispute = await Dispute.findById(req.params.id); if (!dispute) return res.status(404).json({ message: 'Dispute not found.' }); if (!['open', 'reviewing', 'resolved'].includes(req.body.status)) return res.status(400).json({ message: 'Invalid dispute status.' }); dispute.status = req.body.status; if (req.body.resolution !== undefined) dispute.resolution = req.body.resolution; await dispute.save(); res.json(dispute); } catch (error) { next(error); } }
export async function entrepreneurs(req, res, next) { try { res.json(await User.find({ role: 'entrepreneur' }).select('name email location skills entrepreneurApproved available createdAt').sort({ createdAt: -1 })); } catch (error) { next(error); } }
export async function approveEntrepreneur(req, res, next) { try { const user = await User.findById(req.params.id); if (!user || user.role !== 'entrepreneur') return res.status(404).json({ message: 'Entrepreneur not found.' }); if (typeof req.body.approved !== 'boolean') return res.status(400).json({ message: 'Approved must be true or false.' }); user.entrepreneurApproved = req.body.approved; await user.save(); res.json({ id: user.id, entrepreneurApproved: user.entrepreneurApproved }); } catch (error) { next(error); } }
export async function categories(req, res, next) { try { res.json(await Category.find().sort({ kind: 1, name: 1 })); } catch (error) { next(error); } }
export async function createCategory(req, res, next) { try { if (!req.body.name?.trim() || !['product', 'service', 'skill'].includes(req.body.kind)) return res.status(400).json({ message: 'Name and a valid category kind are required.' }); res.status(201).json(await Category.create({ name: req.body.name, kind: req.body.kind })); } catch (error) { if (error.code === 11000) return res.status(409).json({ message: 'That category already exists.' }); next(error); } }
export async function deleteCategory(req, res, next) { try { const result = await Category.findByIdAndDelete(req.params.id); if (!result) return res.status(404).json({ message: 'Category not found.' }); res.status(204).end(); } catch (error) { next(error); } }
export async function commerce(req, res, next) { try { const [orderList, requestList, complaintList] = await Promise.all([Order.find().populate('customer entrepreneur product', 'name title').sort({ createdAt: -1 }), ServiceRequest.find().populate('customer entrepreneur service', 'name title').sort({ createdAt: -1 }), Complaint.find().populate('openedBy', 'name').sort({ createdAt: -1 })]); res.json({ orders: orderList, serviceRequests: requestList, complaints: complaintList }); } catch (error) { next(error); } }
export async function updateComplaint(req, res, next) { try { const complaint = await Complaint.findById(req.params.id); if (!complaint) return res.status(404).json({ message: 'Complaint not found.' }); if (!['open', 'reviewing', 'resolved'].includes(req.body.status)) return res.status(400).json({ message: 'Invalid complaint status.' }); complaint.status = req.body.status; if (req.body.resolution !== undefined) complaint.resolution = req.body.resolution; await complaint.save(); res.json(complaint); } catch (error) { next(error); } }
export async function commerceAnalytics(req, res, next) { try { const [registeredEntrepreneurs, activeUsers, orderCount, serviceRequestCount, completedOrders, completedRequests, ratings, productSales, serviceSales] = await Promise.all([User.countDocuments({ role: 'entrepreneur' }), User.countDocuments({}), Order.countDocuments(), ServiceRequest.countDocuments(), Order.countDocuments({ status: 'completed' }), ServiceRequest.countDocuments({ status: 'completed' }), Review.aggregate([{ $group: { _id: null, value: { $avg: '$rating' } } }]), Order.aggregate([{ $match: { status: 'completed' } }, { $group: { _id: null, value: { $sum: '$total' } } }]), ServiceRequest.aggregate([{ $match: { status: 'completed' } }, { $group: { _id: null, value: { $sum: '$quotedPrice' } } }])]); res.json({ registeredEntrepreneurs, activeUsers, orders: orderCount, serviceRequests: serviceRequestCount, completedOrders, completedServiceRequests: completedRequests, salesVolume: (productSales[0]?.value || 0) + (serviceSales[0]?.value || 0), averageRating: ratings[0]?.value ? Number(ratings[0].value.toFixed(2)) : 0 }); } catch (error) { next(error); } }
