import Product from '../models/Product.js';
import Service from '../models/Service.js';
import Order from '../models/Order.js';
import ServiceRequest from '../models/ServiceRequest.js';
import Review from '../models/Review.js';
import Complaint from '../models/Complaint.js';

const entrepreneur = (user) => user.role === 'entrepreneur' && user.entrepreneurApproved;
const productFields = ['title', 'description', 'category', 'price', 'stock', 'images', 'active'];
const serviceFields = ['title', 'description', 'category', 'price', 'active'];
const productPopulate = [{ path: 'entrepreneur', select: 'name location entrepreneurApproved available' }];
const orderPopulate = [{ path: 'customer', select: 'name email location' }, { path: 'entrepreneur', select: 'name email location' }, { path: 'product', select: 'title images category' }];
const requestPopulate = [{ path: 'customer', select: 'name email location' }, { path: 'entrepreneur', select: 'name email location available' }, { path: 'service', select: 'title category price' }];
const setFields = (target, source, fields) => fields.forEach((field) => { if (source[field] !== undefined) target[field] = source[field]; });

export async function products(req, res, next) { try { const query = { active: true }; if (req.query.entrepreneur) query.entrepreneur = req.query.entrepreneur; if (req.query.category) query.category = new RegExp(`^${req.query.category.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`, 'i'); res.json(await Product.find(query).populate(productPopulate).sort({ createdAt: -1 })); } catch (error) { next(error); } }
export async function product(req, res, next) { try { const item = await Product.findById(req.params.id).populate(productPopulate); if (!item || !item.active) return res.status(404).json({ message: 'Product not found.' }); res.json(item); } catch (error) { next(error); } }
export async function myProducts(req, res, next) { try { res.json(await Product.find({ entrepreneur: req.user.id }).sort({ createdAt: -1 })); } catch (error) { next(error); } }
export async function createProduct(req, res, next) { try { if (!entrepreneur(req.user)) return res.status(403).json({ message: 'Only approved entrepreneurs can publish products.' }); if (!req.body.title || !req.body.category || !Number.isFinite(req.body.price) || !Number.isInteger(req.body.stock) || req.body.price < 1 || req.body.stock < 0) return res.status(400).json({ message: 'Title, category, a positive price, and non-negative integer stock are required.' }); const item = await Product.create({ entrepreneur: req.user.id, ...Object.fromEntries(productFields.filter((f) => req.body[f] !== undefined).map((f) => [f, req.body[f]])) }); res.status(201).json(item); } catch (error) { next(error); } }
export async function updateProduct(req, res, next) { try { const item = await Product.findById(req.params.id); if (!item) return res.status(404).json({ message: 'Product not found.' }); if (item.entrepreneur.toString() !== req.user.id) return res.status(403).json({ message: 'You can only manage your own products.' }); setFields(item, req.body, productFields); await item.save(); res.json(item); } catch (error) { next(error); } }

export async function services(req, res, next) { try { const query = { active: true }; if (req.query.entrepreneur) query.entrepreneur = req.query.entrepreneur; res.json(await Service.find(query).populate(productPopulate).sort({ createdAt: -1 })); } catch (error) { next(error); } }
export async function myServices(req, res, next) { try { res.json(await Service.find({ entrepreneur: req.user.id }).sort({ createdAt: -1 })); } catch (error) { next(error); } }
export async function createService(req, res, next) { try { if (!entrepreneur(req.user)) return res.status(403).json({ message: 'Only approved entrepreneurs can publish services.' }); if (!req.body.title || !req.body.description || !req.body.category || (req.body.price !== undefined && (!Number.isFinite(req.body.price) || req.body.price < 0))) return res.status(400).json({ message: 'Title, description, category, and a valid price are required.' }); res.status(201).json(await Service.create({ entrepreneur: req.user.id, ...Object.fromEntries(serviceFields.filter((f) => req.body[f] !== undefined).map((f) => [f, req.body[f]])) })); } catch (error) { next(error); } }
export async function updateService(req, res, next) { try { const item = await Service.findById(req.params.id); if (!item) return res.status(404).json({ message: 'Service not found.' }); if (item.entrepreneur.toString() !== req.user.id) return res.status(403).json({ message: 'You can only manage your own services.' }); setFields(item, req.body, serviceFields); await item.save(); res.json(item); } catch (error) { next(error); } }

export async function createOrder(req, res, next) { try { const { productId, quantity = 1, orderInfo = {} } = req.body; if (!productId || !Number.isInteger(quantity) || quantity < 1 || quantity > 1000 || !orderInfo.name?.trim() || !orderInfo.contact?.trim() || !orderInfo.address?.trim()) return res.status(400).json({ message: 'Product, valid quantity, name, contact, and address are required.' }); const item = await Product.findById(productId); if (!item || !item.active || item.stock < quantity) return res.status(409).json({ message: 'This product is unavailable in the requested quantity.' }); const update = await Product.updateOne({ _id: item.id, active: true, stock: { $gte: quantity } }, { $inc: { stock: -quantity } }); if (!update.modifiedCount) return res.status(409).json({ message: 'This product is no longer available in the requested quantity.' }); const order = await Order.create({ customer: req.user.id, entrepreneur: item.entrepreneur, product: item.id, quantity, unitPrice: item.price, total: item.price * quantity, orderInfo }); res.status(201).json(await Order.findById(order.id).populate(orderPopulate)); } catch (error) { next(error); } }
export async function orders(req, res, next) { try { const query = req.user.role === 'entrepreneur' ? { entrepreneur: req.user.id } : { customer: req.user.id }; res.json(await Order.find(query).populate(orderPopulate).sort({ createdAt: -1 })); } catch (error) { next(error); } }
export async function transitionOrder(req, res, next) { try { const order = await Order.findById(req.params.id); if (!order) return res.status(404).json({ message: 'Order not found.' }); const action = req.body.action; const isCustomer = order.customer.toString() === req.user.id; const isEntrepreneur = order.entrepreneur.toString() === req.user.id; const permitted = (action === 'confirm' && isEntrepreneur && order.status === 'pending') || (action === 'complete' && isEntrepreneur && order.status === 'confirmed') || (action === 'cancel' && isCustomer && order.status === 'pending'); if (!permitted) return res.status(400).json({ message: 'This order status transition is not allowed.' }); order.status = action === 'confirm' ? 'confirmed' : action === 'complete' ? 'completed' : 'cancelled'; await order.save(); if (action === 'cancel') await Product.findByIdAndUpdate(order.product, { $inc: { stock: order.quantity } }); res.json(await Order.findById(order.id).populate(orderPopulate)); } catch (error) { next(error); } }

export async function createServiceRequest(req, res, next) { try { const { serviceId, details, requestedFor } = req.body; if (!serviceId || !details?.trim()) return res.status(400).json({ message: 'Service and request details are required.' }); if (requestedFor && Number.isNaN(new Date(requestedFor).valueOf())) return res.status(400).json({ message: 'Requested date is invalid.' }); const service = await Service.findById(serviceId).populate('entrepreneur'); if (!service || !service.active) return res.status(404).json({ message: 'Service not found.' }); if (!service.entrepreneur.entrepreneurApproved || !service.entrepreneur.available) return res.status(409).json({ message: 'This entrepreneur is not currently available.' }); if (service.entrepreneur.id === req.user.id) return res.status(400).json({ message: 'You cannot request your own service.' }); res.status(201).json(await ServiceRequest.create({ customer: req.user.id, entrepreneur: service.entrepreneur.id, service: service.id, quotedPrice: service.price, details, requestedFor })); } catch (error) { next(error); } }
export async function serviceRequests(req, res, next) { try { const query = req.user.role === 'entrepreneur' ? { entrepreneur: req.user.id } : { customer: req.user.id }; res.json(await ServiceRequest.find(query).populate(requestPopulate).sort({ createdAt: -1 })); } catch (error) { next(error); } }
export async function transitionServiceRequest(req, res, next) { try { const request = await ServiceRequest.findById(req.params.id); if (!request) return res.status(404).json({ message: 'Service request not found.' }); const action = req.body.action; const mine = request.entrepreneur.toString() === req.user.id; const customer = request.customer.toString() === req.user.id; const permitted = (['accept', 'reject'].includes(action) && mine && request.status === 'pending') || (action === 'start' && mine && request.status === 'accepted') || (action === 'complete' && mine && request.status === 'in_progress') || (action === 'cancel' && customer && request.status === 'pending'); if (!permitted) return res.status(400).json({ message: 'This service request status transition is not allowed.' }); if (action === 'accept') { const owner = await (await import('../models/User.js')).default.findById(req.user.id); if (!owner.available || !owner.entrepreneurApproved) return res.status(409).json({ message: 'You are not available to accept requests.' }); } request.status = ({ accept: 'accepted', reject: 'rejected', start: 'in_progress', complete: 'completed', cancel: 'cancelled' })[action]; await request.save(); res.json(await ServiceRequest.findById(request.id).populate(requestPopulate)); } catch (error) { next(error); } }

export async function reviewsForEntrepreneur(req, res, next) { try { res.json(await Review.find({ entrepreneur: req.params.entrepreneurId }).populate('customer', 'name').sort({ createdAt: -1 })); } catch (error) { next(error); } }
export async function createReview(req, res, next) { try { const { orderId, serviceRequestId, rating, feedback = '' } = req.body; if ((!orderId && !serviceRequestId) || (orderId && serviceRequestId) || !Number.isInteger(rating) || rating < 1 || rating > 5) return res.status(400).json({ message: 'Provide one completed transaction and a rating from 1 to 5.' }); const tx = orderId ? await Order.findById(orderId) : await ServiceRequest.findById(serviceRequestId); if (!tx || tx.customer.toString() !== req.user.id || tx.status !== 'completed') return res.status(403).json({ message: 'You can only review your own completed transaction.' }); const duplicate = await Review.exists(orderId ? { customer: req.user.id, order: orderId } : { customer: req.user.id, serviceRequest: serviceRequestId }); if (duplicate) return res.status(409).json({ message: 'You have already reviewed this transaction.' }); res.status(201).json(await Review.create({ customer: req.user.id, entrepreneur: tx.entrepreneur, order: orderId, serviceRequest: serviceRequestId, rating, feedback })); } catch (error) { next(error); } }
export async function createComplaint(req, res, next) { try { const { orderId, serviceRequestId, reason } = req.body; if ((!orderId && !serviceRequestId) || (orderId && serviceRequestId) || !reason?.trim()) return res.status(400).json({ message: 'Provide one transaction and a reason.' }); const tx = orderId ? await Order.findById(orderId) : await ServiceRequest.findById(serviceRequestId); if (!tx || ![tx.customer.toString(), tx.entrepreneur.toString()].includes(req.user.id)) return res.status(403).json({ message: 'You can only complain about your own transaction.' }); res.status(201).json(await Complaint.create({ openedBy: req.user.id, order: orderId, serviceRequest: serviceRequestId, reason })); } catch (error) { next(error); } }
export async function myComplaints(req, res, next) { try { res.json(await Complaint.find({ openedBy: req.user.id }).sort({ createdAt: -1 })); } catch (error) { next(error); } }
